// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATJIOq7_CzwF3mIemSRc6W9JT4sS_TmFs',
    appId: '1:522611232044:android:cd81f131b16e246713f089',
    messagingSenderId: '522611232044',
    projectId: 'crud-realtime-db-11953',
    databaseURL: 'https://crud-realtime-db-11953-default-rtdb.firebaseio.com',
    storageBucket: 'crud-realtime-db-11953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBuTma3tDMsfNF-sqmLTzlD2ou6weCdc',
    appId: '1:522611232044:ios:bcb32b1678c61ead13f089',
    messagingSenderId: '522611232044',
    projectId: 'crud-realtime-db-11953',
    databaseURL: 'https://crud-realtime-db-11953-default-rtdb.firebaseio.com',
    storageBucket: 'crud-realtime-db-11953.appspot.com',
    iosBundleId: 'com.example.crudRealtimeDb',
  );
}
